-- Phase 1: Add missing HealthEventType values and NotificationType values

ALTER TYPE "HealthEventType" ADD VALUE IF NOT EXISTS 'CULLING';
ALTER TYPE "HealthEventType" ADD VALUE IF NOT EXISTS 'BIRD_WEIGHING';
ALTER TYPE "HealthEventType" ADD VALUE IF NOT EXISTS 'BATCH_SOLD';
ALTER TYPE "HealthEventType" ADD VALUE IF NOT EXISTS 'BATCH_DISCARDED';

ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PURCHASE_REQUEST_RAISED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'LPO_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'LPO_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EGG_BREAKAGE_ADJUSTMENT';
