// src/pages/store/inventory/LposTab.tsx
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Eye, X } from 'lucide-react';
import dayjs from 'dayjs';
import { api } from '../../../lib/api/client';
import { fmtKES, STATUS_BADGE, type LPO } from './_shared';

export function LposTab() {
  const [statusFilter, setStatusFilter] = useState('');
  const [viewing, setViewing] = useState<LPO | null>(null);

  const { data: list = [], isLoading } = useQuery({
    queryKey: ['lpos', statusFilter],
    queryFn: async () => (await api.get('/store/inventory/lpos', { params: statusFilter ? { status: statusFilter } : {} })).data as LPO[],
  });

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-2">
        <p className="text-sm text-gray-500">
          LPOs are generated by the Accountant from reviewed purchase requests. Store can view and track delivery status.
        </p>
        <select value={statusFilter} onChange={e => setStatusFilter(e.target.value)}
          className="ml-auto rounded-xl text-sm border border-gray-200 dark:border-dark-border bg-white dark:bg-gray-800 px-3 py-2">
          <option value="">All statuses</option>
          {['DRAFT','SUBMITTED','APPROVED','RECEIVED','CANCELLED'].map(s => <option key={s} value={s}>{s}</option>)}
        </select>
      </div>

      <div className="bg-white dark:bg-dark-card rounded-2xl border border-gray-100 dark:border-dark-border overflow-hidden">
        {isLoading ? <div className="p-6 text-center text-gray-500 text-sm">Loading…</div>
        : list.length === 0 ? <div className="p-6 text-center text-gray-500 text-sm">No LPOs yet.</div>
        : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="bg-gray-50 dark:bg-gray-800 text-gray-500 text-xs uppercase">
                <tr>
                  <th className="text-left px-4 py-2">LPO #</th>
                  <th className="text-left px-4 py-2">Date</th>
                  <th className="text-left px-4 py-2">Supplier</th>
                  <th className="text-left px-4 py-2">PR Ref</th>
                  <th className="text-right px-4 py-2">Total</th>
                  <th className="text-center px-4 py-2">Status</th>
                  <th className="px-4 py-2"></th>
                </tr>
              </thead>
              <tbody>
                {list.map(l => (
                  <tr key={l.id} className="border-t border-gray-100 dark:border-dark-border">
                    <td className="px-4 py-2 font-mono text-xs">{l.lpoNumber}</td>
                    <td className="px-4 py-2">{dayjs(l.lpoDate).format('YYYY-MM-DD')}</td>
                    <td className="px-4 py-2">{l.supplierName}</td>
                    <td className="px-4 py-2 text-xs font-mono text-gray-500">{l.purchaseRequest?.requestRef ?? '—'}</td>
                    <td className="px-4 py-2 text-right font-semibold">{fmtKES(l.totalKes)}</td>
                    <td className="px-4 py-2 text-center">
                      <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${STATUS_BADGE[l.status] ?? ''}`}>{l.status}</span>
                    </td>
                    <td className="px-4 py-2 text-right">
                      <button onClick={() => setViewing(l)} className="text-brand-green hover:underline text-xs inline-flex items-center gap-1">
                        <Eye className="w-3 h-3" /> View
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {viewing && <LPODetail lpo={viewing} onClose={() => setViewing(null)} />}
    </div>
  );
}

function LPODetail({ lpo, onClose }: { lpo: LPO; onClose: () => void }) {
  return (
    <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
      <div className="bg-white dark:bg-dark-card rounded-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between px-5 py-3 border-b border-gray-100 dark:border-dark-border">
          <div>
            <h3 className="font-bold text-gray-800 dark:text-gray-100">{lpo.lpoNumber}</h3>
            <p className="text-xs text-gray-500">{lpo.supplierName} — {dayjs(lpo.lpoDate).format('YYYY-MM-DD')}</p>
          </div>
          <button onClick={onClose}><X className="w-5 h-5" /></button>
        </div>
        <div className="p-5 space-y-4 text-sm">
          <div className="flex flex-wrap gap-4">
            <div>
              <span className="text-gray-500">Status: </span>
              <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${STATUS_BADGE[lpo.status] ?? ''}`}>{lpo.status}</span>
            </div>
            {lpo.expectedDelivery && <div><span className="text-gray-500">Expected:</span> {dayjs(lpo.expectedDelivery).format('YYYY-MM-DD')}</div>}
            {lpo.purchaseRequest && <div><span className="text-gray-500">PR:</span> <span className="font-mono">{lpo.purchaseRequest.requestRef}</span></div>}
          </div>
          {lpo.notes && <div><span className="text-gray-500">Notes:</span> {lpo.notes}</div>}

          <div>
            <h4 className="font-semibold mb-2">Items</h4>
            <table className="w-full text-xs">
              <thead className="text-gray-500">
                <tr><th className="text-left">Item</th><th className="text-right">Qty</th><th className="text-right">Unit Price</th><th className="text-right">Subtotal</th></tr>
              </thead>
              <tbody>
                {lpo.items.map(i => (
                  <tr key={i.id} className="border-t border-gray-100 dark:border-dark-border">
                    <td className="py-1">{i.storeItem?.name ?? i.description}</td>
                    <td className="text-right">{Number(i.quantity)} {i.storeItem?.unit}</td>
                    <td className="text-right">{fmtKES(i.unitPrice)}</td>
                    <td className="text-right">{fmtKES(i.subtotal)}</td>
                  </tr>
                ))}
              </tbody>
              <tfoot className="text-right">
                <tr><td colSpan={3} className="pt-2 text-gray-500">Subtotal</td><td className="pt-2">{fmtKES(lpo.subtotalKes)}</td></tr>
                <tr><td colSpan={3} className="text-gray-500">VAT</td><td>{fmtKES(lpo.vatKes)}</td></tr>
                <tr className="font-bold border-t border-gray-200 dark:border-dark-border"><td colSpan={3} className="pt-2">Total</td><td className="pt-2">{fmtKES(lpo.totalKes)}</td></tr>
              </tfoot>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}
